apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:oauth-servercert-trust
  namespace: openshift-config-managed
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:openshift:oauth-servercert-trust
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
