apiVersion: v1
clusters:
- name: local-cluster
  cluster:
    certificate-authority-data: ${CA_DATA}
    server: https://${APISERVER_IP}/apis/oauth.openshift.io/v1/tokenreviews
    tls-server-name: api.openshift-oauth-apiserver.svc
contexts:
- name: local-context
  context:
    cluster: local-cluster
    user: openshift-authenticator
current-context: local-context
kind: Config
users:
- name: openshift-authenticator
  user:
    client-certificate-data: ${CLIENT_CERT}
    client-key-data: ${CLIENT_KEY}